# Task 1

#### Write a function to compute 5/0 and use try/except to catch the exceptions.

In [2]:
def divide(x, y):
    try:
        result = x / y
        print("Your answer is :", result)
    except ZeroDivisionError:
        print("Sorry ! You are dividing by zero")
        

divide(5,2)

divide(5,0)

Your answer is : 2.5
Sorry ! You are dividing by zero


#### Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [5]:
subjects = ["Americans", "Indians"] 
verbs = ["Play", "watch"]
objects = ["Baseball","cricket"]

for x in subjects:
    for y in verbs:
        for z in objects:
            print(x+" "+y+" "+z+".")


Americans Play Baseball.
Americans Play cricket.
Americans watch Baseball.
Americans watch cricket.
Indians Play Baseball.
Indians Play cricket.
Indians watch Baseball.
Indians watch cricket.


# Task 2

In [10]:
'''
Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, 
the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde.
'''

import numpy as np
x = np.array([2,3,4,1])
n = 5

np.vander(x,n)

array([[ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [  1,   1,   1,   1,   1]])

In [11]:
np.vander(x,n,increasing=False)

array([[ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [  1,   1,   1,   1,   1]])

In [12]:
np.vander(x,n,increasing=True)

array([[  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   1,   1,   1,   1]])

In [13]:
#When 'n' is not mentioned, a square array is returned.
np.vander(x,increasing=False)

array([[ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1],
       [ 1,  1,  1,  1]])